[project]
name = "idv-server"
dynamic = ["version"]
description = "IDV server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hypercorn>=0.17.3",
    "strawberry-graphql[asgi]>=0.275.5",
    "typer>=0.16.0",
]

[project.scripts]
idv-server = "idv_server.__main__:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "./idv_server/__about__.py"
