"""initial migration

Revision ID: 652d26e0c5a4
Revises:
Create Date: 2025-07-01 23:05:37.741313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "652d26e0c5a4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hct_root_tone", sa.Integer(), nullable=True),
        sa.Column("bg_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("favicon_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("issuer_id", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("claim_expires_at", sa.DateTime(), nullable=False),
        sa.Column("verification_expires_at", sa.DateTime(), nullable=False),
        sa.Column("ticket_expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "NOT_CLAIMED",
                "AUTH_ISSUED",
                "BASIC_INFORMATION_SUBMITTED",
                "VERIFICATION_STARTED",
                "VERIFICATION_FINISHED",
                name="ticketstage",
            ),
            nullable=False,
        ),
        sa.Column("user_verdict", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "user_verdict_type",
            sa.Enum(
                "ACCEPTED", "REJECTED", "SERVICE_UNAVAILABLE", name="userverdicttype"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["application.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "basicinformation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "country_of_primary_residence",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_id"),
    )
    op.create_table(
        "metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "verificationinformation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("verifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "EXPIRED",
                "REJECTED_TEMPORARILY",
                "REJECTED_PERMANENTLY",
                "ACCEPTED",
                name="ticketverificationverdict",
            ),
            nullable=False,
        ),
        sa.Column("verdict_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "verdict_human_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "authenticity",
            sa.Enum("STRONG", "MANUAL", "NOT_VERIFIED", name="authenticitytype"),
            nullable=True,
        ),
        sa.Column(
            "ownership",
            sa.Enum("STRONG", "MANUAL", "NOT_VERIFIED", name="ownershiptype"),
            nullable=True,
        ),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verificationinformation")
    op.drop_table("metadata")
    op.drop_table("basicinformation")
    op.drop_table("ticket")
    op.drop_table("application")
    # ### end Alembic commands ###
